# Generated by Django 4.2 on 2023-04-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_partipantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='partipantes',
            new_name='participantes',
        ),
    ]
